# Generated by Django 5.0.1 on 2024-02-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_scheduler_author_vacationrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VacationRequest',
            new_name='HolidayRequest',
        ),
    ]
