# Generated by Django 5.0.1 on 2024-02-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_scheduler_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduler',
            name='author',
        ),
        migrations.DeleteModel(
            name='HolidayRequest',
        ),
    ]
