# Generated by Django 5.0.1 on 2024-02-07 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_holidayrequest'),
        ('knox', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('authtoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='knox.authtoken')),
            ],
            bases=('knox.authtoken',),
        ),
    ]
