# Generated by Django 5.0.1 on 2024-02-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
