# Generated by Django 5.0.2 on 2024-02-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_delete_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
