# Generated by Django 5.0.2 on 2024-02-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_holidayrequest_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
