# Generated by Django 5.0.1 on 2024-02-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_holidayrequest_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayType',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
    ]
