# Generated by Django 5.0.1 on 2024-03-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_notification_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFrom', models.DateField()),
                ('dateTo', models.DateField()),
            ],
        ),
    ]
