# Generated by Django 5.0.1 on 2024-03-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_holidayplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayrequest',
            name='color_hex',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
