# Generated by Django 5.0.1 on 2024-03-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_date_customuser_iddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='annualSettlementAddress',
            new_name='annual_settlement_address',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='correspondenceAddress',
            new_name='correspondence_address',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='idData',
            new_name='id_data',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='idDate',
            new_name='id_date',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='idGivenBy',
            new_name='id_given_by',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='nfzBranch',
            new_name='nfz_branch',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='taxOffice',
            new_name='tax_office',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='userResidenceData',
            new_name='user_residenceData',
        ),
    ]
