# Generated by Django 5.0.1 on 2024-03-13 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_annualsettlementaddress_customuser_annual_settlement_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_residenceData',
            new_name='user_residence_data',
        ),
    ]
