# Generated by Django 5.0.1 on 2024-03-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_customuser_city_customuser_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='municipalCommune',
            new_name='municipal_commune',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='postalCode',
            new_name='postal_code',
        ),
    ]
