# Generated by Django 5.0.1 on 2024-03-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_customuser_id_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='city',
            new_name='city_correspondence',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='flat_number',
            new_name='city_permanent_residence',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='house_number',
            new_name='city_second_residence',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='country',
            new_name='country_correspondence',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='municipal_commune',
            new_name='flat_number_correspondence',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='post',
            new_name='flat_number_permanent_residence',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='postal_code',
            new_name='flat_number_second_residence',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='street',
            new_name='house_number_correspondence',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='voivodeship',
            new_name='house_number_permanent_residence',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='mobile_number',
            new_name='mobile_number_correspondence',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_residence_data',
        ),
        migrations.AddField(
            model_name='customuser',
            name='country_permanent_residence',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country_second_residence',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='house_number_second_residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile_number_permanent_residence',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile_number_second_residence',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='municipal_commune_correspondence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='municipal_commune_permanent_residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='municipal_commune_second_residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='post_correspondence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='post_permanent_residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='post_second_residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postal_code_correspondence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postal_code_permanent_residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postal_code_second_residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='street_correspondence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='street_permanent_residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='street_second_residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='voivodeship_correspondence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='voivodeship_permanent_residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='voivodeship_second_residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
