# Generated by Django 5.0.1 on 2024-03-20 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_city_customuser_city_correspondence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20)),
                ('nfz_branch', models.CharField(default='', max_length=100)),
                ('id_data', models.CharField(default='', max_length=100)),
                ('id_given_by', models.CharField(default='', max_length=100)),
                ('id_date', models.DateField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
