# Generated by Django 5.0.1 on 2024-03-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_datachangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datachangerequest',
            name='id_data',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='datachangerequest',
            name='id_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='datachangerequest',
            name='id_given_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datachangerequest',
            name='nfz_branch',
            field=models.CharField(max_length=50),
        ),
    ]
