# Generated by Django 5.0.1 on 2024-03-21 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_datachangerequest_id_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datachangerequest',
            name='id_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
