# Generated by Django 5.0.1 on 2024-03-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_remove_datachangerequest_annual_settlement_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datachangerequest',
            name='annual_settlement_address',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='tax_office',
            field=models.TextField(blank=True, default='', max_length=70),
        ),
    ]
