# Generated by Django 5.0.1 on 2024-03-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_datachangerequest_annual_settlement_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datachangerequest',
            name='city_correspondence_residence',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='city_permanent_residence',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='city_second_residence',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='correspondence_address',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='country_correspondence_residence',
            field=models.TextField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='country_permanent_residence',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='country_second_residence',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='flat_number_correspondence_residence',
            field=models.TextField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='flat_number_permanent_residence',
            field=models.TextField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='flat_number_second_residence',
            field=models.TextField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='house_number_correspondence_residence',
            field=models.TextField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='house_number_permanent_residence',
            field=models.TextField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='house_number_second_residence',
            field=models.TextField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='mobile_number_correspondence_residence',
            field=models.TextField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='mobile_number_permanent_residence',
            field=models.TextField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='mobile_number_second_residence',
            field=models.TextField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='municipal_commune_correspondence_residence',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='municipal_commune_permanent_residence',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='municipal_commune_second_residence',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='post_correspondence_residence',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='post_permanent_residence',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='post_second_residence',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='postal_code_correspondence_residence',
            field=models.TextField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='postal_code_permanent_residence',
            field=models.TextField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='postal_code_second_residence',
            field=models.TextField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='street_correspondence_residence',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='street_permanent_residence',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='street_second_residence',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='voivodeship_correspondence_residence',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='voivodeship_permanent_residence',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datachangerequest',
            name='voivodeship_second_residence',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='datachangerequest',
            name='tax_office',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
    ]
