# Generated by Django 5.0.1 on 2024-04-16 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_holidayrequestplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayrequestplan',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 12, 19, 58, 18665, tzinfo=datetime.timezone.utc)),
        ),
    ]
