# Generated by Django 5.0.1 on 2024-04-16 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_holidayrequestplan_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayrequestplan',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 17, 0, 13, 627791, tzinfo=datetime.timezone.utc)),
        ),
    ]
